sudo: required
dist: trusty
language: cpp
notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libgtest-dev
    - build-essential
    - cmake
before_install:
  - cd /usr/src/gtest && sudo cmake . && sudo make && sudo mv libg* /usr/lib/ && cd -
install:
  - cmake .
  - make VERBOSE=1
script: 
  - ./unittests
